[package]
name = "kasina-render"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
bytemuck.workspace = true
egui.workspace = true
egui-wgpu.workspace = true
parking_lot.workspace = true

[dev-dependencies]
naga.workspace = true

[[bench]]
name = "prepare_visual_frame"
harness = false

[lints]
workspace = true
